swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "2.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get User Transactions
      description: Retrieve all transactions for the current month, grouped by account, for the authenticated user
      parameters:
        - name: month
          in: query
          type: string
          description: Month for which transactions should be retrieved
          required: true
        - name: account
          in: query
          type: string
          description: Account for which transactions should be retrieved
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/TransactionList"
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: Retrieve details of a specific transaction for the authenticated user
      parameters:
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to retrieve
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/account/transaction/{transactionId}/edit/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update category of transaction
      description: API for fetching a user profile to update transaction category
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          description: User's transaction ID
          type: integer
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/BodyEditTransactionCategory"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction category update successfully
          schema:
            $ref: "#/definitions/EditTransactionCategory"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/account/transaction/{transactionId}/edit/notes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update notes of transaction
      description: API for fetching a user profile to update transaction note
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          description: User's transaction ID
          type: integer
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/BodyEditTransactionNote"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction note update successfully
          schema:
            $ref: "#/definitions/EditTransactionNote"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionList:
    type: array
    items:
      $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: id of transaction
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      date:
        type: string
        example: 2016-08-29T09:12:33.001+0000
        description: transaction date
        format: date-time
      description:
        type: string
        description: description of the transaction
        example: Golden sun Bakery
      amount:
        type: number
        description: transaction amount($)
        example: 100.00
      balance:
        type: number
        description: Balance after the transaction
        example: 900.00
      type:
        type: string
        description: type of transaction
        example: Deposit
      notes:
        type: string
        description: notes of transaction
        example: Transfer from my current account
      category:
        type: string
        description: category of transaction
        example: Food
  BodyEditTransactionCategory:
    type: object
    description: Edit category of transaction
    properties:
      category:
        type: string
        description: category of transaction
        example: Car's repair
  EditTransactionCategory:
    type: object
    description: Api response
    properties:
      status:
        type: integer
      message:
        type: string
      category:
        type: string
        description: category of transaction
        example: Car's repair
  BodyEditTransactionNote:
    type: object
    description: Edit notes of transaction
    properties:
      comment:
        type: string
        description: notes of transaction
        example: Transfer from my current account
  EditTransactionNote:
    type: object
    description: Api response
    properties:
      status:
        type: integer
      message:
        type: string
      comment:
        type: string
        description: notes of transaction
        example: Transfer from my current account
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: "#/definitions/Transaction"
