swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "2.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get User Transactions
      description: Retrieve all transactions for the current month, grouped by account, for the authenticated user
      parameters:
        - name: month
          in: query
          type: string
          description: Month for which transactions should be retrieved
        - name: account
          in: query
          type: string
          description: Account for which transactions should be retrieved
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/TransactionList"
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add Transaction
      description: Add a new transaction for the authenticated user
      parameters:
        - in: body
          name: body
          description: New transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: Retrieve details of a specific transaction for the authenticated user
      parameters:
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to retrieve
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction
      description: Update information for a specific transaction for the authenticated user
      parameters:
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to update
          required: true
        - in: body
          name: body
          description: Updated transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete Transaction
      description: Delete a specific transaction for the authenticated user
      parameters:
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to delete
          required: true
      responses:
        "204":
          description: Successful operation, no content
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionList:
    type: array
    items:
      $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: id of transaction
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      date:
        type: string
        example: 2016-08-29T09:12:33.001+0000
        description: transaction date
        format: date-time
      description:
        type: string
        description: description of the transaction
        example: Golden sun Bakery
      amount:
        type: number
        description: transaction amount($)
        example: 100.00
      balance:
        type: number
        description: Balance after the transaction
        example: 900.00
      type:
        type: string
        description: type of transaction
        example: Deposit
      comment:
        type: string
        description: notes of transaction
        example: Transfer from my current account
      category:
        type: string
        description: category of transaction
        example: Food
  TransactionInput:
    type: object
    properties:
      type:
        type: string
        description: type of transaction
        example: Deposit
      comment:
        type: string
        description: notes of transaction
        example: Transfer from my current account
      category:
        type: string
        description: category of transaction
        example: Food
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: "#/definitions/Transaction"
